import { useSelector } from 'react-redux'
import Head from 'next/head'
import MenuHeader from '../../../components/interface/menu/MenuHeader'
import Sidebar from '../../../components/interface/sidebar'
import { RootState } from '../../../store'

import Modal from '../../../components/interface/modal'

const Page: React.FC = () => {
  const { isSidebarOpen } = useSelector((state: RootState) => state.sidebar)
  const baseMainContentWrapper = `flex-1 min-h-screen bg-gray-500 transform duration-300 mb-52 pt-12`
  return (
    <>
      <Head>
        <title>Pertinent CMS - Studio page</title>
        <meta name="description" content="Generated by create next app" />
      </Head>
      <main className="flex">
        <MenuHeader />
        <div
          className={
            isSidebarOpen ? `${baseMainContentWrapper} pr-72` : `${baseMainContentWrapper}`
          }
        >
          Main content
        </div>
        <Sidebar />
        <Modal />
      </main>
    </>
  )
}

export default Page
