import Link from 'next/link'
import Head from 'next/head'
import 'tailwindcss/tailwind.css'
import { getSiteInformation } from '../../api/site'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'
import MenuHeader from '../../components/interface/menu/MenuHeader'

interface Page {
  name: string
  id: string
  path: string
}

export const getServerSideProps: GetServerSideProps = async () => {
  const result = await getSiteInformation()
  const pages: Page[] = result.data
  return {
    props: {
      pages,
    },
  }
}

const Studio: React.FC = ({ pages }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const baseMainContentWrapper = `flex-1 min-h-screen transform duration-300 pt-12`
  return (
    <>
      <Head>
        <title>Pertinent CMS - Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={baseMainContentWrapper}>
        <MenuHeader />
        <div>
          {pages.map((page: Page) => {
            return (
              <Link key={page.id} href={`studio/page/${page.id}`}>
                <a>{page.name}</a>
              </Link>
            )
          })}
        </div>
      </main>
    </>
  )
}

export default Studio
