import Link from 'next/link'
import Head from 'next/head'
import { getSiteInformation } from '../../api/site'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'

interface Page {
  name: string
  id: string
  path: string
}

export const getServerSideProps: GetServerSideProps = async () => {
  const result = await getSiteInformation()
  const pages: Page[] = result.data
  return {
    props: {
      pages,
    },
  }
}

const Studio: React.FC = ({ pages }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  return (
    <div>
      <Head>
        <title>Pertinent CMS - Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main>
        {pages.map((page: Page) => {
          return (
            <Link key={page.id} href={`studio/page/${page.id}`}>
              <a>{page.name}</a>
            </Link>
          )
        })}
      </main>
    </div>
  )
}

export default Studio
