import Head from 'next/head'
import { GetServerSideProps, InferGetServerSidePropsType } from 'next'

import { getSiteInformation } from '../../api/site'
import MenuHeader from '../../components/interface/menu/MenuHeader'
import { Page } from '../../types/pages'
import PageItem from '../../components/pages/PageItem'
import Modal from '../../components/interface/modal'

import { useDispatch } from 'react-redux'
import { openModal } from '../../store/actions/modal'
import { ADD_PAGE } from '../../store/types/modal'

export const getServerSideProps: GetServerSideProps = async () => {
  const result = await getSiteInformation()
  const pages: Page[] = result.data
  return {
    props: {
      pages,
    },
  }
}

const Studio: React.FC = ({ pages }: InferGetServerSidePropsType<typeof getServerSideProps>) => {
  const dispatch = useDispatch()

  const handleModalAddPage = (): void => {
    dispatch(openModal(ADD_PAGE))
  }
  const baseMainContentWrapper = `flex-1 min-h-screen transform duration-300 pt-12`
  return (
    <>
      <Head>
        <title>Pertinent CMS - Studio</title>
        <meta name="description" content="Generated by create next app" />
      </Head>

      <main className={baseMainContentWrapper}>
        <MenuHeader />
        <div className="container w-4/5 md:w-2/3 lg:w-1/2 mx-auto">
          <div className="flex flex-row justify-between items-center pr-4">
            <div className="pt-4">
              <h2 className="text-2xl font-bold">Pages</h2>
              <p>Description of the page section</p>
            </div>
            <button className="btn btn-add h-8" onClick={handleModalAddPage}>
              Add new page
            </button>
          </div>
          <div className="flex flex-col mt-6">
            {pages.map((page: Page) => {
              return <PageItem page={page} key={page.id} />
            })}
          </div>
        </div>
        <Modal />
      </main>
    </>
  )
}

export default Studio
